### ISSUE TITLE
Problems about the high velocity error of motor speed

### ISSUE THREAD

**Issue by laniakeawhite** [open-dynamic-robot-initiative/udriver_firmware#11]
Hello!
i am doing test to control the motor rotate at some speed. The control code is modified from

https://github.com/open-dynamic-robot-initiative/python_blmc/blob/master/scripts/velocity_ctrl.py

When controling the motor,i also plot the desired speed,actual speed and the error in real time.

Here is the plot:
![image](https://user-images.githubusercontent.com/104501826/190938139-f12970d1-2c64-43a3-b478-d6995c643447.png)
![image](https://user-images.githubusercontent.com/104501826/190938195-7c941ef6-310b-492d-ae51-b0a77f1065cc.png)

1. red line is the desired speed
2. green line is the actual speed
3. blue line is the velocity error

I have check the motor_board.cpp of BLMC_drivers to make sure that the actual speed
is already in rad/s,not krpm.

As you can see that the actual speed seems very noisy.

Here is my question:
1. The velocity error interval is [-50,25], i think this is bad. does this means there is some problems with my encoder wheel?
2. Can anyone tell me what the normal velocity error interval is expected?
3. Does the speed needs some filtering?I try the low pass filter,the result is not good.

When i am doing the test, the error with error code=1 occurs sometimes,so i modified the udriver.
from
```
#define QEP_MAX_INDEX_ERROR (1./360.) * USER_MOTOR_ENCODER_LINES
```
to
```
#define QEP_MAX_INDEX_ERROR (10./360.) * USER_MOTOR_ENCODER_LINES
```

Does this make the encoder more inaccurate?

Best Regards！

**Comment by luator** [comment]
I answered to the [corresponding question in the ODRI forum](https://odri.discourse.group/t/problems-about-the-high-velocity-error-of-motor-speed/615) and suggest to continue the discussion there.
