### ISSUE TITLE
Problem about code patch

### ISSUE THREAD

**Issue by laniakeawhite** [open-dynamic-robot-initiative/udriver_firmware#9]
Hi every one
I am trying to compile the udriver_firmware under ubuntu 18.04.

I do the step-by-step job descripted in :
https://open-dynamic-robot-initiative.github.io/mw_dual_motor_torque_ctrl/build_instructions.html

When i do the code patch,there are some error show in the terminal as below:
```
Hunk #1 FAILED at 2 (different link endings).
....

6 out of 8 hunks FAILED.--................
```

Do those error matter?
How I can fix those errors?

**Comment by laniakeawhite** [comment]
My OS is Ubuntu 18.04, so i install the MotorWare in windows,then copy files into fireware_can/motorware.
I think this maybe the problem,so i use a tool named dos2unix  to format the related files. 
It works,the hunks failed error disappeared.

There is another problem,  compile fail because of the follow error:
```
#1965 cannot open source file "user1.h"
#1965 cannot open source file "user2.h"
```
I check the include path, there are no files named "user1.h" and "user2.h",and then i check the motorware folder,there  6 files named "user1.h" and 6 files named "user2.h".

CCS version is 9.1.0, i don't know how to solve this problem.
Does anyboy can help me ?

**Comment by luator** [comment]
Hello,
Thanks for letting us know about the line-ending issue!

Regarding the missing user*.h: These files should be found in `firmware/config_f28069m_drv8305` (they are modified copies of the ones coming with motorware).  They are loaded as submodule, so you have to either clone with `git clone --recursive ...` or you can afterwards load them with `git submodule update --init --recursive`.

**Comment by laniakeawhite** [comment]
Yes , comile is passed if i use the command "git clone --recursive ...".

Thanks.
